// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TileServer.Models;

#nullable disable

namespace TileServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227220627_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TileServer.Models.MonitoredRoute.MonitoredRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OriginLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MonitoredRoutes");
                });

            modelBuilder.Entity("TileServer.Models.TrafficLog.LogPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrafficLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrafficLogId");

                    b.ToTable("LogPoint");
                });

            modelBuilder.Entity("TileServer.Models.TrafficLog.TrafficLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FreeFlowSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrafficDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TravelTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("TileServer.Models.TrafficLog.LogPoint", b =>
                {
                    b.HasOne("TileServer.Models.TrafficLog.TrafficLog", "TrafficLog")
                        .WithMany("Points")
                        .HasForeignKey("TrafficLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrafficLog");
                });

            modelBuilder.Entity("TileServer.Models.TrafficLog.TrafficLog", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
